# Generated by Django 5.1.5 on 2025-01-27 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_like',
        ),
        migrations.AddField(
            model_name='post',
            name='users_save',
            field=models.ManyToManyField(blank=True, related_name='posts_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
